manifest:
  remotes:
    - name: lexxpluss
      url-base: https://github.com/LexxPluss
  projects:
    - name: zephyr
      remote: lexxpluss
      revision: lexxpluss/main
      import: true
    - name: ros_msgs
      remote: lexxpluss
      revision: main
      path: ros_msgs
  self:
    path: lexxpluss_apps
