name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zephyrprojectrtos/zephyr-build:latest
      options: --user root
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout private zephyr
        uses: actions/checkout@v2
        with:
          repository: LexxPluss/zephyr
          token: ${{ secrets.GH_PAT }}
          path: zephyr
      - name: Checkout private LexxAuto
        uses: actions/checkout@v2
        with:
          repository: LexxPluss/LexxAuto
          token: ${{ secrets.GH_PAT }}
          path: LexxAuto
      - name: build
        id: build
        run: |
          set -e
          west init -l zephyr
          west update
          west zephyr-export
          ZEPHYR_TOOLCHAIN_VARIANT=gnuarmemb west build -b lexxpluss_mb01 lexxpluss_apps
      - name: Notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#div-02-robotics-ci'
        if: always()
